### ISSUE TITLE
Exposed Username and password in URI

### ISSUE THREAD

**Issue by eth0izzle** [kiocosta/Omnistack#1]
**Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@omnistack-yyhky.mongodb.net` in file [/backend/src/server.js](https://github.com/kiocosta/Omnistack/blob/master/backend/src/server.js)<br/><br/>You should recycle your credentials immediately and move secrets to environment variables to prevent them being committed to GitHub.

**Comment by kiocosta** [comment]
> **Potential security breach**. Verified credentials in URL `*redacted*:*redacted*@omnistack-yyhky.mongodb.net` in file [/backend/src/server.js](https://github.com/kiocosta/Omnistack/blob/master/backend/src/server.js)
> 
> You should recycle your credentials immediately and move secrets to environment variables to prevent them being committed to GitHub.

Huge thanks for letting me know about this!
I've fixed the issue!
